server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/** 
        - id: customer
          uri: http://localhost:8083
          predicates:
            - Path=/custormers/** /myPages/**
        - id: bookInventory
          uri: http://localhost:8084
          predicates:
            - Path=/books/**/deliverables/**/stockInputs/** 
        - id: point
          uri: http://localhost:8085
          predicates:
            - Path=/points/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/custormers/** /myPages/**
        - id: bookInventory
          uri: http://bookInventory:8080
          predicates:
            - Path=/books/**/deliverables/**/stockInputs/** 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
